---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 8

inputs:
  - name: samples-repo
caches:
  - path: maven
  - path: gradle

run:
  path: samples-repo/ci/scripts/run-tests.sh
